services:
  - type: web
    name: vmake-product-catalog
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        # Replace with your actual PostgreSQL database URL
        # Format: postgres://username:password@host:port/database?sslmode=require
        value: YOUR_DATABASE_URL_HERE # IMPORTANT: Replace with your actual database URL
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_WHATSAPP
        # Replace with your admin WhatsApp number
        value: YOUR_ADMIN_WHATSAPP_NUMBER # IMPORTANT: Replace with your admin WhatsApp number
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: AUTH_RATE_LIMIT_MAX_REQUESTS
        value: 5
      - key: MAX_FILE_SIZE
        value: 104857600
